name: recipes_app
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  get: ^4.6.6
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.1.0
  get_storage: ^2.1.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  flutter_native_splash: ^2.4.0
  sqflite: ^2.3.3+1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/images/logo/

  
  

  
  

  
  
  
  
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  
  
  
  
  
  
  
  
  
  
